name: amazing workflow demo

on:
  workflow_dispatch:
    inputs:
      stage1_trigger:
        description: 'Deploy to Development environment?'
        required: false
        default: 'false'
        type: choice
        options: ['false', 'true']
      stage2_trigger:
        description: 'Deploy to Production environment?'
        required: false
        default: 'false'
        type: choice
        options: ['false', 'true']
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  build:
    name: Build the artifact
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.decide.outputs.artifact_name }}
      run_modify: ${{ steps.decide.outputs.run_modify }}
    steps:
    - name: Build an artifact
      run: echo "This step builds an artifact"

    - name: Decide what happens next
      id: decide
      run: |
        echo "Evaluating next steps..."
        if [[ "${{ github.event_name }}" == "push" && ( "${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == refs/tags/v* ) ]]; then
          echo "artifact_name=modified-artifact" >> $GITHUB_OUTPUT
          echo "run_modify=true" >> $GITHUB_OUTPUT
          echo "Expect: modify + deploy"
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.stage2_trigger }}" == "true" ]]; then
          echo "artifact_name=modified-artifact" >> $GITHUB_OUTPUT
          echo "run_modify=true" >> $GITHUB_OUTPUT
          echo "Expect: modify + prod deploy"
        else
          echo "artifact_name=original-artifact" >> $GITHUB_OUTPUT
          echo "run_modify=false" >> $GITHUB_OUTPUT
          echo "Expect: direct deploy"
        fi

  modify:
    name: Modify the artifact
    needs: build
    if: needs.build.outputs.run_modify == 'true'
    environment: Production
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.set.outputs.artifact_name }}
    steps:
    - name: Modify the artifact
      run: echo "This step downloads the artifact and alters it"

    - name: Update artifact name
      id: set
      run: echo "artifact_name=modified-artifact" >> $GITHUB_OUTPUT

  deploy-to-dev:
    name: Deploy to Development
    needs: build
    if: |
      github.event_name == 'workflow_dispatch' && github.event.inputs.stage1_trigger == 'true' ||
      github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Determine artifact name
      id: artifact
      run: |
        echo "artifact_name=${{ needs.build.outputs.artifact_name }}" >> $GITHUB_ENV

    - name: Deploy to development
      run: |
        echo "Deploying $artifact_name to Dev"

  deploy-to-prod:
    name: Deploy to Production
    environment: Requires-Approval
    needs: build
    if: |
      github.event_name == 'workflow_dispatch' && github.event.inputs.stage2_trigger == 'true' ||
      github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - name: Determine artifact name
      id: artifact
      run: |
        echo "artifact_name=${{ needs.build.outputs.artifact_name }}" >> $GITHUB_ENV

    - name: Deploy to production
      run: |
        echo "Deploying $artifact_name to Production"
